"""Add bed tracking and expiry dates

Revision ID: b105c87025ab
Revises: c5fd636114de
Create Date: 2026-07-08 18:04:12.243337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b105c87025ab'
down_revision: Union[str, Sequence[str], None] = 'c5fd636114de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('occupied_beds', sa.Integer(), nullable=True))
    op.add_column('stocks', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'expiry_date')
    op.drop_column('facilities', 'occupied_beds')
    # ### end Alembic commands ###
